name: CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Connect to server and deploy changes
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASS }}
          port: 22
          script: |
            pm2 stop task-tracker.rakhmatulloh.uz
            cd task-tracker
            git pull origin main
            rm -rf ./build
            rm -rf /var/www/task-tracker.rakhmatulloh.uz
            mkdir /var/www/task-tracker.rakhmatulloh.uz
            npm install
            npm run build
            cp -rf ./build/* /var/www/task-tracker.rakhmatulloh.uz
            pm2 restart task-tracker.rakhmatulloh.uz
